common: &common
  franchises_snapshot_location: '/Volumes/{catalog}/landing/franchises/{run_id}.parquet'
  catalog: catalog

#     landing_databricks_vol: 

#   theaters:
#     landing_databricks_vol: /Volumes/{catalog}/landing/theaters/{run_id}.parquet

#   showtimes:
#     landing_databricks_vol: /Volumes/{catalog}/landing/showtimes/{run_id}/{snashot_ts}_{id}.jsonl
  
#   seatmaps:
#     landing_databricks_vol: /Volumes/{catalog}/landing/seatmaps/{run_id}/{snapshot_ts}_{id}.jsonl

#   tmp:
#     bq_dataset: fandango_tmp
#   snapshots:
#     dataset: fandango_snapshots
#   datalake:
#     bq_dataset: fandango
#     bucket_name: fandango_data


# crawler:
#   navigation: &navigation
#     retry: 3

#   seatPage:
#     <<: *navigation
#     retry: 1

#   areaPage:
#     <<: *navigation

dev:
  <<: *common
  catalog: fandango_dev